version: "3.8"

services:
  api:
    build: api
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  app:
    build: app
    depends_on:
      - api
    ports:
      - "4200:4200"

  mongo:
    image: mongo:4.4.4
